version: '3'
services:

# The middleware part
  middleware:
    image: afakharany/g2csv_middleware
    network_mode: "host"
    depends_on: 
      - scraper
# The scraper part
  scraper:
    image: afakharany/g2csv_scraper
    network_mode: "host"
# The frontend part
  web:
    image: afakharany/g2csv_nginx
    ports:
      - 8000:80
    depends_on:
      - middleware
      - scraper
    network_mode: "host"