version: '3'
services:

# The middleware part
  middleware:
    image: middleware
# The scraper part
  scraper:
    image: scraper
# The frontend part
  web:
    image: nginx
    ports:
      - 80:80
    volumes:
      - "./web/g2csv.conf:/etc/nginx/conf.d/g2csv.conf"
