apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: g2scv-scraper
spec:
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: scraper
    spec:
      containers:
        - image: afakharany/g2csv_scraper
          imagePullPolicy: Always
          name: g2csv-scraper
          ports:
            - containerPort: 5000